### ISSUE TITLE
Any clues about BCU1525 QSFP28 pinout?

### ISSUE THREAD

**Issue by YangWang92** [d953i/Custom_Part_Data_Files#1]
Thanks for sharing! It works on my BCU1525.

BTW, I cannot find any details about QSFP28 pinouts on BCU1525, is it possible to share this part? 

Thanks a lot!

**Comment by d953i** [comment]
I believe they are the same as on Alveo U200 and you can find constraints for it at https://github.com/Xilinx/XilinxBoardStore/blob/2018.3/boards/Xilinx/au200/1.1/part0_pins.xml

**Comment by YangWang92** [comment]
Thanks a lot!
