### ISSUE TITLE
How to get in contact with you ?

### ISSUE THREAD

**Issue by developeralgo8888** [d953i/Custom_Part_Data_Files#2]
Any email or way to contact you. i have an opportunity to design  VCU1525 boards which are high performing low power mining boards and manufacture  FPGA PCB Board  and then then users can add/install VCU9P, VCU13P chips or any other  that fits the socket 

Memory on the Board  HBM2 or GDDR6  64 GB  ( 16 GB x 4 )  or 32 GB ( 8 Gb x 4 )  but remove all other unnecessary parts and only optimize for mining different crypto currencies  but also can be chained as a cluster . The Cluster part is very import to be able to cheaply build a chained cluster

Let Me Know regards 
jacob

**Comment by d953i** [comment]
We can talk on FPGA mining discord: https://discord.gg/jJ797Br4
